# Generated by Django 4.0.5 on 2022-06-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skippings', '0002_mymodel_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('reason', models.CharField(max_length=400)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
